name: stardylog
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.4.0
  firebase_auth: ^5.2.1
  google_sign_in: ^6.2.1
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  intl: ^0.19.0
  lucide_flutter: ^0.544.0
  flutter_svg: ^2.0.10+1
  simple_icons: ^14.6.1
  fl_chart: ^1.1.1
  fl_chart_flutter: ^0.70.3
  cupertino_icons: ^1.0.8


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/google_logo.svg
    - assets/icons/kakao_logo.svg