// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8-3icaMoWPprKpyAHDtaWtA30SV5zTAI',
    appId: '1:520849174357:web:12921b1edd1b8d185f49dc',
    messagingSenderId: '520849174357',
    projectId: 'stardylog',
    authDomain: 'stardylog.firebaseapp.com',
    storageBucket: 'stardylog.firebasestorage.app',
    measurementId: 'G-YK0L49PLPK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAE75gdNrIiHnQ3PHyg9CBiXp359PnvZRQ',
    appId: '1:520849174357:android:d08afe7d97bc07815f49dc',
    messagingSenderId: '520849174357',
    projectId: 'stardylog',
    storageBucket: 'stardylog.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKIG8mgmjFKCt9SBOSEy68AakZtb6TjX8',
    appId: '1:520849174357:ios:194dfbd19d2c58ff5f49dc',
    messagingSenderId: '520849174357',
    projectId: 'stardylog',
    storageBucket: 'stardylog.firebasestorage.app',
    androidClientId: '520849174357-b3aogqnlbfeatnp5rg5bf4069kalhc7l.apps.googleusercontent.com',
    iosClientId: '520849174357-l9recdjhurjuc39lkf8ks88hn5v40u0i.apps.googleusercontent.com',
    iosBundleId: 'com.example.stardylog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKIG8mgmjFKCt9SBOSEy68AakZtb6TjX8',
    appId: '1:520849174357:ios:194dfbd19d2c58ff5f49dc',
    messagingSenderId: '520849174357',
    projectId: 'stardylog',
    storageBucket: 'stardylog.firebasestorage.app',
    androidClientId: '520849174357-b3aogqnlbfeatnp5rg5bf4069kalhc7l.apps.googleusercontent.com',
    iosClientId: '520849174357-l9recdjhurjuc39lkf8ks88hn5v40u0i.apps.googleusercontent.com',
    iosBundleId: 'com.example.stardylog',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8-3icaMoWPprKpyAHDtaWtA30SV5zTAI',
    appId: '1:520849174357:web:19480fe6a7ab60e15f49dc',
    messagingSenderId: '520849174357',
    projectId: 'stardylog',
    authDomain: 'stardylog.firebaseapp.com',
    storageBucket: 'stardylog.firebasestorage.app',
    measurementId: 'G-ZT7LCYYTQ1',
  );
}
